name: 'Pull Request Reviewer'
description: 'Reviews pull requests using Gemini AI to identify bugs, suggest improvements, and optimize performance'
author: 'Tomas Roda'
branding:
  icon: 'eye'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/index.js'
  env:
    NODE_OPTIONS: '--experimental-vm-modules'
