on:
  pull_request:
    types: [opened, reopened]

jobs:
  analyze_pr:
    runs-on: ubuntu-latest
    name: A job to analyze a PR with an LLM
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout action
        uses: actions/checkout@v4
      - name: Install action packages
        shell: 'bash'
        run: npm install
      - name: PullRequestAnalyzer
        uses: ./ # Uses an action in the root directory
        id: analyze_pr
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          geminiApiKey: ${{ secrets.GEMINI_API_KEY }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.analyze_pr.outputs.time }}"
