on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr_review:
    runs-on: ubuntu-latest
    name: A job to review a PR with an LLM
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout action
        uses: actions/checkout@v4
      - name: Pull Request Reviewer
        uses: rodat-dev/pr-review-action@v1.0.0
        id: pr_review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Get the output time
        run: echo "The time was ${{ steps.review_pr.outputs.time }}"
