on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'AutoReadme'
    name: A job to say hello
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # To use this private repository's action,
      # you must check out the repository:
      - name: Checkout action
        uses: actions/checkout@v4
      # - name: Install action packages
      #   shell: 'bash'
      #   run: npm install
      - name: PR Reader
        uses: ./ # Uses an action in the root directory
        id: pr-reader
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.pr-reader.outputs.time }}"
